apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom-statsd-exporter-app
  namespace: prometheus
spec:
  interval: 5m0s
  install: 
    disableWait: true  
    crds: Create
  upgrade:
    crds: CreateReplace
    disableWait: true
  chart:
    spec:
      chart: prometheus-statsd-exporter
      version: '0.13.1'
      sourceRef:
        kind: HelmRepository
        name: prom-charts
        namespace: flux-system
      interval: 5m0s
  valuesFrom:
  - kind: ConfigMap
    name: prom-statsd-exporter-app-values