apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: prometheus
spec:
  ports:
  - name: web
    port: 9104
    targetPort: 9104
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysqld-exporter
  namespace: prometheus
subsets:
- addresses:
  - ip: 10.9.3.63
  ports:
  - name: web
    port: 9104
    protocol: TCP
