# Client MySQL-Exporter Service
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: prometheus
  labels:
    app: mysqld-exporter
spec:
  type: ExternalName
  externalName: 10.9.3.63
  ports:
    - name: mysql-metrics
      protocol: TCP
      port: 9104
      targetPort: 9104
---
# Client Blackbox-Exporter Service
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: prometheus
  labels:
    app: blackbox-exporter
spec:
  type: ExternalName
  externalName: 10.9.3.63
  ports:
    - name: blackbox-metrics
      protocol: TCP
      port: 9115
      targetPort: 9115
---
# Client Node-Exporter Service
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: prometheus
  labels:
    app: node-exporter
spec:
  type: ExternalName
  externalName: 10.9.3.63
  ports:
    - name: node-exporter-metrics
      protocol: TCP
      port: 9100
      targetPort: 9100