apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - pvc.yaml
  # - scale.yaml
  
# config for automatic reconciliation
spec:
  interval: 1m
  retryInterval: 30s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

configMapGenerator:
- name: prometheus-app-values
  namespace: prometheus
  files:
    - values.yaml=prometheus-app-values.yaml
configurations:
  - kustomizeconfig.yaml