apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-app
  namespace: prometheus
spec:
  interval: 3m0s
  install: 
    disableWait: true  
    crds: Create
  upgrade:
    crds: CreateReplace
    disableWait: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '58.2.2'
      sourceRef:
        kind: HelmRepository
        name: prom-charts
        namespace: flux-system
      interval: 3m0s
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-app-values