apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml

configMapGenerator:
- name: ingress-nginx-app-values
  namespace: ingress-nginx
  files:
    - values.yaml=ingress-nginx-app-values.yaml
configurations:
  - kustomizeconfig.yaml