apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-app
  namespace: ingress-nginx
spec:
  interval: 5m0s
  install: 
    disableWait: true  
    crds: Create
  upgrade:
    crds: CreateReplace
    disableWait: true
  chart:
    spec:
      chart: ingress-nginx
      version: '4.10.1'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-chart
        namespace: flux-system
      interval: 5m0s
  valuesFrom:
  - kind: ConfigMap
    name: ingress-nginx-app-values