---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-app
  namespace: ingress-nginx
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ingress-nginx
      version: '4.10.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 5m0s
  valuesFrom:
  - kind: ConfigMap
    name: ingress-nginx-app-values  
        