apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom-mysql-exporter-app
  namespace: prometheus
spec:
  interval: 3m0s
  install: 
    disableWait: true  
    crds: Create
  upgrade:
    crds: CreateReplace
    disableWait: true
  chart:
    spec:
      chart: prometheus-mysql-exporter
      version: '2.5.2'
      sourceRef:
        kind: HelmRepository
        name: prom-charts
        namespace: flux-system
      interval: 3m0s
  valuesFrom:
  - kind: ConfigMap
    name: prom-mysql-exporter-app-values