apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  # - scale.yaml

configMapGenerator:
- name: prom-blackbox-app-values
  namespace: prometheus
  files:
    - values.yaml=prom-blackbox-app-values.yaml
configurations:
  - kustomizeconfig.yaml