apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom-blackbox-app
  namespace: prom-blackbox
spec:
  interval: 5m0s
  install: 
    disableWait: true  
    crds: Create
  upgrade:
    crds: CreateReplace
    disableWait: true
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: '8.16.0'
      sourceRef:
        kind: HelmRepository
        name: prom-charts
        namespace: flux-system
      interval: 5m0s
  valuesFrom:
  - kind: ConfigMap
    name: prom-blackbox-app-values